POST http://localhost:3333/polls
content-type: application/json

{
    "title": "Biscoito ou bolacha?",
    "options": ["Biscoito", "Bolacha"]
}

###

GET http://localhost:3333/polls/d956e37f-2c01-4a38-aa2a-eb69fb810775

###

POST http://localhost:3333/polls/d956e37f-2c01-4a38-aa2a-eb69fb810775/votes
content-type: application/json

{
    "pollOptionId": "fd4d7b94-0c25-4681-9b08-cea896aa5097"
}
